Repository NCATComp410/comp410_summer_2025, pull requests merged in 2025-07, with the labels that each got.

#19 Add US_SSN test case
  test_team_null.py
Labels: TeamNULL

#21 Add AU_ABN test case
  pii_scan.py
  test_team_1.py
Labels: Team1

#20 Add PHONE_NUMBER test case
  test_team_4.py
Labels: Team4

#25 Add Person test case
  test_team_4.py
Labels: Team4

#27 Add US_Passport test case
  test_team_4.py
Labels: Team4

#35 Update test_team_3.py
  test_team_3.py
Labels: Team3

#22 Add EMAIL_ADDRESS test cases
  test_team_2.py
Labels: Team2

#33 12 detect us bank number
  test_team_3.py
Labels: Team3

#32 Add CRYPTO test case
  test_team_2.py
Labels: Team2

#31 Added AU_TFN
  test_team_1.py
Labels: Team1

#37 Update test_team_3.py
  test_team_3.py
Labels: Team3
